TICKERS = [
    "RELIANCE.NS",
    "TCS.NS",
    "HDFCBANK.NS",
    "ITC.NS",
    "GOLDBEES.NS"
]

START_DATE = "2018-01-01"
END_DATE = None

CONFIDENCE_LEVEL = 0.95
TRADING_DAYS = 252
MONTE_CARLO_PATHS = 10000
